/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author USER
 */
import java.sql.*;
import javax.swing.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import net.proteanit.sql.DbUtils;

public class SecondPage extends javax.swing.JFrame {

    /**
     * Creates new form SecondPage
     */
    Connection conn=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    private ImageIcon format = null;
    
     
    public SecondPage() throws SQLException {
        initComponents();
         conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/tv", "root", "1234567");
            //pst = conn.createStatement();
            chid.setText(Global.chID);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DisplayBut = new javax.swing.JButton();
        AddShowBut = new javax.swing.JButton();
        AddAdBut = new javax.swing.JButton();
        DelShowBut = new javax.swing.JButton();
        DelAdBut = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        homePageBut = new javax.swing.JButton();
        BufferedImage = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        chid = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        DisplayBut.setText("Display");
        DisplayBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayButActionPerformed(evt);
            }
        });

        AddShowBut.setText("Add Show");
        AddShowBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddShowButActionPerformed(evt);
            }
        });

        AddAdBut.setText("Add Advertisement");
        AddAdBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddAdButActionPerformed(evt);
            }
        });

        DelShowBut.setText("Delete Show");
        DelShowBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DelShowButActionPerformed(evt);
            }
        });

        DelAdBut.setText("Delete Advertisement");
        DelAdBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DelAdButActionPerformed(evt);
            }
        });

        jButton1.setText("Update Show");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Update Ad");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        homePageBut.setText(" Home Page");
        homePageBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homePageButActionPerformed(evt);
            }
        });

        jButton3.setText("Channel Icon");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chid, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(homePageBut))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AddShowBut, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                            .addComponent(AddAdBut, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                        .addGap(0, 45, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(DelShowBut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DelAdBut, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3)
                            .addComponent(BufferedImage, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(90, 90, 90)
                        .addComponent(DisplayBut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(homePageBut, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(BufferedImage, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(DisplayBut)
                        .addGap(34, 34, 34)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddShowBut)
                    .addComponent(DelShowBut)
                    .addComponent(jButton1))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddAdBut)
                    .addComponent(DelAdBut)
                    .addComponent(jButton2))
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddShowButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddShowButActionPerformed
        // TODO add your handling code here:
        AddShow add = new AddShow();
        add.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_AddShowButActionPerformed

    private void AddAdButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddAdButActionPerformed
        // TODO add your handling code here:
        AddAdvertisment advt = new AddAdvertisment();
        advt.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_AddAdButActionPerformed

    private void DelShowButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DelShowButActionPerformed
        // TODO add your handling code here:
        DeleteShow dltshw = new DeleteShow();
        dltshw.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_DelShowButActionPerformed

    private void DelAdButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DelAdButActionPerformed
        // TODO add your handling code here:
        DeleteAd dltbt = new DeleteAd();
        dltbt.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_DelAdButActionPerformed

    private void DisplayButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayButActionPerformed
        // TODO add your handling code here:
        DisplayShows dispshw = new DisplayShows();
        dispshw.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_DisplayButActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        UpdateShow upsh = new UpdateShow();
        upsh.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        UpdateAD ad = new UpdateAD();
        ad.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void homePageButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homePageButActionPerformed
        // TODO add your handling code here:
        FrontPage frtpg = new FrontPage();
        frtpg.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_homePageButActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
       //String sql="select * from hall ";
        try{
         /*   pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            JOptionPane.showMessageDialog(null,"Search completed");
            
            available_table.setModel(DbUtils.resultSetToTableModel(rs));
           */
            String sql = "select img from channel where channel_id = ?";
            
            pst=conn.prepareStatement(sql);
           pst.setString(1,chid.getText());
            rs=pst.executeQuery();
            
            if(rs.next()){
                 
                byte[]imagedate = rs.getBytes("img");
                format = new ImageIcon(imagedate);
                BufferedImage.setIcon(format);
            }
       
        
            
            
      }
        catch(Exception e){
            e.printStackTrace();
         JOptionPane.showMessageDialog(null,e);
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddAdBut;
    private javax.swing.JButton AddShowBut;
    private javax.swing.JLabel BufferedImage;
    private javax.swing.JButton DelAdBut;
    private javax.swing.JButton DelShowBut;
    private javax.swing.JButton DisplayBut;
    private javax.swing.JTextField chid;
    private javax.swing.JButton homePageBut;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    // End of variables declaration//GEN-END:variables
}
